<?php

namespace Database\Seeders;

use App\Models\Subscription;
use Illuminate\Database\Seeder;

class SubscriptionSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Basic',
                'name_ar' => 'أساسي',
                'description' => 'Perfect for individuals with light laundry needs',
                'description_ar' => 'مثالي للأفراد ذوي احتياجات الغسيل الخفيفة',
                'price' => 199.00,
                'validity' => 1,
                'validity_type' => 'months',
                'laundry_credits' => 50,
                'clothing_credits' => 50,
                'delivery_credits' => 2,
                'towel_credits' => 5,
                'special_credits' => 5,
                'features' => json_encode([
                    '50 Laundry Credits',
                    '2 Free Deliveries',
                    'Standard Support',
                    'Mobile App Access',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3498db',
            ],
            [
                'name' => 'Standard',
                'name_ar' => 'قياسي',
                'description' => 'Great value for small families',
                'description_ar' => 'قيمة رائعة للعائلات الصغيرة',
                'price' => 399.00,
                'validity' => 1,
                'validity_type' => 'months',
                'laundry_credits' => 100,
                'clothing_credits' => 100,
                'delivery_credits' => 4,
                'towel_credits' => 10,
                'special_credits' => 10,
                'features' => json_encode([
                    '100 Laundry Credits',
                    '4 Free Deliveries',
                    'Priority Support',
                    'Mobile App Access',
                    'Express Service Available',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'color' => '#9b59b6',
            ],
            [
                'name' => 'Premium',
                'name_ar' => 'مميز',
                'description' => 'Best value for families - Most Popular!',
                'description_ar' => 'أفضل قيمة للعائلات - الأكثر شعبية!',
                'price' => 599.00,
                'validity' => 1,
                'validity_type' => 'months',
                'laundry_credits' => 200,
                'clothing_credits' => 200,
                'delivery_credits' => 8,
                'towel_credits' => 20,
                'special_credits' => 20,
                'features' => json_encode([
                    '200 Laundry Credits',
                    '8 Free Deliveries',
                    'Priority Support',
                    'Mobile App Access',
                    'Express Service Included',
                    'Special Items Discount',
                ]),
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
                'color' => '#f39c12',
            ],
            [
                'name' => 'VIP',
                'name_ar' => 'كبار الشخصيات',
                'description' => 'Ultimate package for large families and businesses',
                'description_ar' => 'الباقة المثالية للعائلات الكبيرة والشركات',
                'price' => 999.00,
                'validity' => 1,
                'validity_type' => 'months',
                'laundry_credits' => 500,
                'clothing_credits' => 500,
                'delivery_credits' => 20,
                'towel_credits' => 50,
                'special_credits' => 50,
                'features' => json_encode([
                    '500 Laundry Credits',
                    '20 Free Deliveries',
                    'VIP Support 24/7',
                    'Mobile App Access',
                    'Express Service Included',
                    'Special Items Discount',
                    'Dedicated Account Manager',
                    'Priority Pickup',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 4,
                'color' => '#e74c3c',
            ],
            [
                'name' => 'Annual Basic',
                'name_ar' => 'سنوي أساسي',
                'description' => 'Save 15% with annual subscription',
                'description_ar' => 'وفر 15% مع الاشتراك السنوي',
                'price' => 1999.00,
                'validity' => 1,
                'validity_type' => 'years',
                'laundry_credits' => 600,
                'clothing_credits' => 600,
                'delivery_credits' => 24,
                'towel_credits' => 60,
                'special_credits' => 60,
                'features' => json_encode([
                    '600 Laundry Credits (50/month)',
                    '24 Free Deliveries',
                    'Priority Support',
                    'Mobile App Access',
                    '15% Savings vs Monthly',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 5,
                'color' => '#27ae60',
            ],
            [
                'name' => 'Annual Premium',
                'name_ar' => 'سنوي مميز',
                'description' => 'Best annual value - Save 20%',
                'description_ar' => 'أفضل قيمة سنوية - وفر 20%',
                'price' => 5999.00,
                'validity' => 1,
                'validity_type' => 'years',
                'laundry_credits' => 2400,
                'clothing_credits' => 2400,
                'delivery_credits' => 96,
                'towel_credits' => 240,
                'special_credits' => 240,
                'features' => json_encode([
                    '2400 Laundry Credits (200/month)',
                    '96 Free Deliveries',
                    'VIP Support 24/7',
                    'Mobile App Access',
                    'Express Service Included',
                    'Special Items Discount',
                    '20% Savings vs Monthly',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 6,
                'color' => '#1abc9c',
            ],
        ];

        foreach ($plans as $plan) {
            Subscription::updateOrCreate(
                ['name' => $plan['name']],
                $plan
            );
        }
    }
}
